routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('landing_page2');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('admin/home', 'AdminController@index');
Route::get('librarian/home', 'LibrarianController@index');

Route::get('admin', 'Admin\LoginController@showLoginForm')->name('admin.login');
Route::post('admin', 'Admin\LoginController@login');

Route::post('admin-password/email', 'Admin\ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
Route::get('admin-password/reset', 'Admin\ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
Route::post('admin-password/reset', 'Admin\ResetPasswordController@reset');
Route::get('admin-password/reset/{token}', 'Admin\ResetPasswordController@showResetForm')->name('admin.password.reset');

Route::get('verify/{email}/{verifyToken}', 'Auth\RegisterController@sendEmailDone')->name('sendEmailDone');


Route::group(array('prefix'=>'librarian'), function()
{
    Route::resource('books', 'BookController');
    Route::get('/member', function () { return view('pages.librarian.member'); });
});

Route::group(array('prefix'=>'home'), function()
{
    Route::get('/inbox', function () { return view('pages.auth.inbox'); });
	Route::get('/task', function () { return view('pages.auth.task'); });
});





	// ===============================================
    // 404 ===========================================
    // ===============================================

    // App::missing(function($exception)
    // {

    //     // shows an error page (app/views/error.blade.php)
    //     // returns a page not found error
    //     return Response::view('error', array(), 404);
    // });

app/Http/Controllers/LibrarianController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class LibrarianController extends Controller
{
	/**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth:admin');
        $this->middleware('librarian');
    }

    public function index()
    {
        return view('pages.librarian.home');
    }
}

resources/views/pages/librarian/books.blade.php
@extends('pages.librarian.home')

@section('content')
	    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_title">
            <h2>Books <small>data</small></h2>
            <ul class="nav navbar-right panel_toolbox">
              <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                <ul class="dropdown-menu" role="menu">
                  <li><a href="#">Settings 1</a>
                  </li>
                  <li><a href="#">Settings 2</a>
                  </li>
                </ul>
              </li>
              <li><a class="close-link"><i class="fa fa-close"></i></a>
              </li>
            </ul>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <table id="datatable-buttons" class="table table-striped table-bordered">
              <thead>
                <tr>
                  <th>ID</th>
                  <th>title</th>
                  <th>ISBN</th>
                  <th>Edition</th>
                  <th>Volume</th>
                  <th>Publisher</th>
                  <th>
                    <button type="button" class="btn btn-info btn-sm" data-toggle="modal" data-target="#myModal">
                      <i class="glyphicon glyphicon-plus"></i> New Data
                    </button>
                  </th>
                </tr>
              </thead>
              <tbody>
            {{ csrf_field() }}
			<?php $no=1; ?>

			@foreach ($books as $key => $value)
                <tr>
                  <td>{{ $no++ }}</td>
                  <td>{{ $value->title }}</td>
                  <td>{{ $value->isbn }}</td>
                  <td>{{ $value->edition }}</td>
                  <td>{{ $value->volume }}</td>
                  <td>{{ $value->name }}</td>
                  <td>
                    <a href="#" class="edit-modal btn btn-warning btn-sm" data-mytitle="{{ $value->title }}" data-myisbn="{{ $value->isbn }}" data-myedition="{{ $value->edition }}" data-myvolume="{{ $value->volume }}" data-myissue="{{ $value->issue }}" data-mycover="{{ $value->cover }}" data-bookid="{{$value->id}}" data-toggle="modal" data-target="#edit">
                        <i class="fa fa-pencil"></i>
                    </a>
                    &nbsp
                    <a href="#" class="delete-modal btn btn-danger btn-sm" data-toggle="modal" data-target="#delete">
                        <i class="fa fa-trash"></i>
                    </a>
                  </td>
                </tr>
			@endforeach
              </tbody>
            </table>
          </div>
        </div>
      </div>


  <!-- Modal New Books-->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">New Books</h4>
        </div>
        <form action="{{route('books.store')}}" method="POST" class="form-horizontal form-label-left">
          {{csrf_field()}}
          <div class="modal-body">
            
            @include('pages.librarian.form.addBooks')

          </div>

          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <button type="reset" class="btn btn-danger">Reset</button>
            <button type="submit" class="btn btn-primary">Save</button>
          </div>
        </form>
      </div>
      
    </div>
  </div>

  <!-- Modal Edit Books-->
  <div class="modal fade" id="edit" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Edit Books</h4>
        </div>
        <form action="{{route('books.update', 1)}}" method="post" class="form-horizontal form-label-left">
          {{method_field('patch')}}
          {{csrf_field()}}
          <div class="modal-body">

            <input type="hidden" name="book_id" id="book_id" value="" >
            @include('pages.librarian.form.editBooks')

          </div>

          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Save Changes</button>
          </div>
        </form>
      </div>
      
    </div>
  </div>


  <!-- Modal Delete Books-->
  <div class="modal fade" id="delete" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Delete Books</h4>
        </div>
        <form action="{{route('books.destroy', 'asd')}}" method="post" class="form-horizontal form-label-left">
          {{method_field('delete')}}
          {{csrf_field()}}
          <div class="modal-body">
            <p><center>
              <h3>Are you sure want to delete this ?</h3>
            </p></center>
            <input type="hidden" name="book_id" id="book_id" value="">

          </div>

          <div class="modal-footer">
            <button type="button" class="btn btn-success" data-dismiss="modal">No</button>
            <button type="submit" class="btn btn-warning">Yes, Delete</button>
          </div>
        </form>
      </div>
      
    </div>
  </div>
@endsection

resources/views/pages/librarian/ebooks.blade.php
@extends('pages.librarian.home')

@section('content')

  <!-- page content -->
  <div class="right_col" role="main">
    <div class="">
      <div class="page-title">
        <div class="title_left">
          <h3> Media Gallery <small> gallery design</small> </h3>
        </div>

        <div class="title_right">
          <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Search for...">
              <span class="input-group-btn">
                  <button class="btn btn-default" type="button">Go!</button>
              </span>
            </div>
          </div>
        </div>
      </div>

      <div class="clearfix"></div>

      <div class="row">
        <div class="col-md-12">
          <div class="x_panel">
            <div class="x_title">
              <h2>Media Gallery <small> gallery design </small></h2>
              <ul class="nav navbar-right panel_toolbox">
                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="#">Settings 1</a>
                    </li>
                    <li><a href="#">Settings 2</a>
                    </li>
                  </ul>
                </li>
                <li><a class="close-link"><i class="fa fa-close"></i></a>
                </li>
              </ul>
              <div class="clearfix"></div>
            </div>
            <div class="x_content">

              <div class="row">

                <p>Media gallery design emelents</p>

                <div class="col-md-55">
                  <div class="thumbnail">
                    <div class="image view view-first">
                      <img style="width: 100%; display: block;" src="images/media.jpg" alt="image" />
                      <div class="mask">
                        <p>Your Text</p>
                        <div class="tools tools-bottom">
                          <a href="#"><i class="fa fa-link"></i></a>
                          <a href="#"><i class="fa fa-pencil"></i></a>
                          <a href="#"><i class="fa fa-times"></i></a>
                        </div>
                      </div>
                    </div>
                    <div class="caption">
                      <p>Snow and Ice Incoming for the South</p>
                    </div>
                  </div>
                </div>
                <div class="col-md-55">
                  <div class="thumbnail">
                    <div class="image view view-first">
                      <img style="width: 100%; display: block;" src="images/media.jpg" alt="image" />
                      <div class="mask">
                        <p>Your Text</p>
                        <div class="tools tools-bottom">
                          <a href="#"><i class="fa fa-link"></i></a>
                          <a href="#"><i class="fa fa-pencil"></i></a>
                          <a href="#"><i class="fa fa-times"></i></a>
                        </div>
                      </div>
                    </div>
                    <div class="caption">
                      <p>Snow and Ice Incoming for the South</p>
                    </div>
                  </div>
                </div>
                <div class="col-md-55">
                  <div class="thumbnail">
                    <div class="image view view-first">
                      <img style="width: 100%; display: block;" src="images/media.jpg" alt="image" />
                      <div class="mask">
                        <p>Your Text</p>
                        <div class="tools tools-bottom">
                          <a href="#"><i class="fa fa-link"></i></a>
                          <a href="#"><i class="fa fa-pencil"></i></a>
                          <a href="#"><i class="fa fa-times"></i></a>
                        </div>
                      </div>
                    </div>
                    <div class="caption">
                      <p>Snow and Ice Incoming for the South</p>
                    </div>
                  </div>
                </div>
                <div class="col-md-55">
                  <div class="thumbnail">
                    <div class="image view view-first">
                      <img style="width: 100%; display: block;" src="images/media.jpg" alt="image" />
                      <div class="mask">
                        <p>Your Text</p>
                        <div class="tools tools-bottom">
                          <a href="#"><i class="fa fa-link"></i></a>
                          <a href="#"><i class="fa fa-pencil"></i></a>
                          <a href="#"><i class="fa fa-times"></i></a>
                        </div>
                      </div>
                    </div>
                    <div class="caption">
                      <p>Snow and Ice Incoming for the South</p>
                    </div>
                  </div>
                </div>
                <div class="col-md-55">
                  <div class="thumbnail">
                    <div class="image view view-first">
                      <img style="width: 100%; display: block;" src="images/media.jpg" alt="image" />
                      <div class="mask">
                        <p>Your Text</p>
                        <div class="tools tools-bottom">
                          <a href="#"><i class="fa fa-link"></i></a>
                          <a href="#"><i class="fa fa-pencil"></i></a>
                          <a href="#"><i class="fa fa-times"></i></a>
                        </div>
                      </div>
                    </div>
                    <div class="caption">
                      <p>Snow and Ice Incoming for the South</p>
                    </div>
                  </div>
                </div>


                <div class="col-md-55">
                  <div class="thumbnail">
                    <div class="image view view-first">
                      <img style="width: 100%; display: block;" src="images/media.jpg" alt="image" />
                      <div class="mask no-caption">
                        <div class="tools tools-bottom">
                          <a href="#"><i class="fa fa-link"></i></a>
                          <a href="#"><i class="fa fa-pencil"></i></a>
                          <a href="#"><i class="fa fa-times"></i></a>
                        </div>
                      </div>
                    </div>
                    <div class="caption">
                      <p><strong>Image Name</strong>
                      </p>
                      <p>Snow and Ice Incoming</p>
                    </div>
                  </div>
                </div>
                <div class="col-md-55">
                  <div class="thumbnail">
                    <div class="image view view-first">
                      <img style="width: 100%; display: block;" src="images/media.jpg" alt="image" />
                      <div class="mask no-caption">
                        <div class="tools tools-bottom">
                          <a href="#"><i class="fa fa-link"></i></a>
                          <a href="#"><i class="fa fa-pencil"></i></a>
                          <a href="#"><i class="fa fa-times"></i></a>
                        </div>
                      </div>
                    </div>
                    <div class="caption">
                      <p><strong>Image Name</strong>
                      </p>
                      <p>Snow and Ice Incoming</p>
                    </div>
                  </div>
                </div>
                <div class="col-md-55">
                  <div class="thumbnail">
                    <div class="image view view-first">
                      <img style="width: 100%; display: block;" src="images/media.jpg" alt="image" />
                      <div class="mask no-caption">
                        <div class="tools tools-bottom">
                          <a href="#"><i class="fa fa-link"></i></a>
                          <a href="#"><i class="fa fa-pencil"></i></a>
                          <a href="#"><i class="fa fa-times"></i></a>
                        </div>
                      </div>
                    </div>
                    <div class="caption">
                      <p><strong>Image Name</strong>
                      </p>
                      <p>Snow and Ice Incoming</p>
                    </div>
                  </div>
                </div>
                <div class="col-md-55">
                  <div class="thumbnail">
                    <div class="image view view-first">
                      <img style="width: 100%; display: block;" src="images/media.jpg" alt="image" />
                      <div class="mask no-caption">
                        <div class="tools tools-bottom">
                          <a href="#"><i class="fa fa-link"></i></a>
                          <a href="#"><i class="fa fa-pencil"></i></a>
                          <a href="#"><i class="fa fa-times"></i></a>
                        </div>
                      </div>
                    </div>
                    <div class="caption">
                      <p><strong>Image Name</strong>
                      </p>
                      <p>Snow and Ice Incoming</p>
                    </div>
                  </div>
                </div>
                <div class="col-md-55">
                  <div class="thumbnail">
                    <div class="image view view-first">
                      <img style="width: 100%; display: block;" src="images/media.jpg" alt="image" />
                      <div class="mask no-caption">
                        <div class="tools tools-bottom">
                          <a href="#"><i class="fa fa-link"></i></a>
                          <a href="#"><i class="fa fa-pencil"></i></a>
                          <a href="#"><i class="fa fa-times"></i></a>
                        </div>
                      </div>
                    </div>
                    <div class="caption">
                      <p><strong>Image Name</strong>
                      </p>
                      <p>Snow and Ice Incoming</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- /page content -->

@endsection

resources/views/pages/librarian/home.blade.php
@extends('layouts.admin.app')

@section('quick_profile')
	<div class="profile_pic">
	    <img src="{{ asset('assets/home_admin/images/lib.png') }}" alt="..." class="img-circle profile_img">
	</div>
	<div class="profile_info">
		<span>Welcome,</span>
		{{-- <h2>{{ Auth::user()->name }}</h2> --}}
	</div>
@endsection

@section('sidebar')
	  <div class="menu_section">
	    <h3>General</h3>
	    <ul class="nav side-menu">
	      <li><a href="/librarian/home"><i class="fa fa-home"></i>Dashboard</a></li>
	      <li><a><i class="fa fa-book"></i> Manage Books <span class="fa fa-chevron-down"></span></a>
	        <ul class="nav child_menu">
	          <li><a href="/librarian/books">Books</a></li>
	          <li><a href="/librarian/ebooks">E-Books</a></li>
	      		<li><a href="#"> -- Categories </a></li>
	        </ul>
	      </li>
	      <li><a><i class="fa fa-users"></i> Manage Members <span class="fa fa-chevron-down"></span></a>
	        <ul class="nav child_menu">
	          <li><a href="/librarian/member">User</a></li>
	          <li><a href="form_advanced.html">E-Books</a></li>
	      		<li><a href="#"> -- Categories </a></li>
	        </ul>
	      </li>
	      <li><a href="#"><i class="fa fa-random"></i>Donation</a></li>
	      <li><a href="#"><i class="fa fa-area-chart"></i>Borrowed Books</a></li>
	      <li><a href="#"><i class="fa fa-area-chart"></i>Daily Read Books</a></li>
	      <li><a href="#"><i class="fa fa-home"></i>Requested Books</a></li>
	      <li><a href="#"><i class="fa fa-home"></i>Report</a></li>
	    </ul>
	  </div>
@endsection

@section('content')
<head>

    <!-- Datatables -->
    <link href="{{ asset('assets/home_admin/vendors/datatables.net-bs/css/dataTables.bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ asset('assets/home_admin/vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ asset('assets/home_admin/vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ asset('assets/home_admin/vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ asset('assets/home_admin/vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css') }}" rel="stylesheet">
  </head>
  
			<div class="row top_tiles">
				<div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
					<div class="tile-stats" style="background:#00c0ef;">
						<a href="/librarian/books">
							<div class="icon"><i class="fa fa-caret-square-o-right"></i></div>
							<div class="count" style="color:white;">1515</div>
							<h3 style="color:white;">Books</h3>
						</a>
					</div>
				</div>
				<div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
					<div class="tile-stats" style="background:#00a65a;">
						<a href="#">
							<div class="icon"><i class="fa fa-comments-o"></i></div>
							<div class="count" style="color:white;">0</div>
							<h3 style="color:white;">Borrowed Books</h3>
						</a>
					</div>
				</div>
				<div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
					<div class="tile-stats" style="background:#dd4b39;">
						<a href="#">
							<div class="icon"><i class="fa fa-sort-amount-desc"></i></div>
							<div class="count" style="color:white;">Return</div>
							<h3 style="color:white;">Books</h3>
						</a>
					</div>
				</div>
				<div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
					<div class="tile-stats" style="background:#dd4b39;">
						<a href="#">
							<div class="icon"><i class="fa fa-check-square-o"></i></div>
							<div class="count" style="color:white;">Issue</div>
							<h3 style="color:white;">Books</h3>
						</a>
					</div>
				</div>
			</div>
@endsection

<!-- Datatables -->
    <script src="{{ asset('assets/home_admin/vendors/datatables.net/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('assets/home_admin/vendors/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>
    <script src="{{ asset('assets/home_admin/vendors/datatables.net-buttons/js/dataTables.buttons.min.js') }}"></script>
    <script src="{{ asset('assets/home_admin/vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js') }}"></script>
    <script src="{{ asset('assets/home_admin/vendors/datatables.net-buttons/js/buttons.flash.min.js') }}"></script>
    <script src="{{ asset('assets/home_admin/vendors/datatables.net-buttons/js/buttons.html5.min.js') }}"></script>
    <script src="{{ asset('assets/home_admin/vendors/datatables.net-buttons/js/buttons.print.min.js') }}"></script>
    <script src="{{ asset('assets/home_admin/vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js') }}"></script>
    <script src="{{ asset('assets/home_admin/vendors/datatables.net-keytable/js/dataTables.keyTable.min.js') }}"></script>
    <script src="{{ asset('assets/home_admin/vendors/datatables.net-responsive/js/dataTables.responsive.min.js') }}"></script>
    <script src="{{ asset('assets/home_admin/vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js') }}"></script>
    <script src="{{ asset('assets/home_admin/vendors/datatables.net-scroller/js/dataTables.scroller.min.js') }}"></script>
    <script src="{{ asset('assets/home_admin/vendors/jszip/dist/jszip.min.js') }}"></script>
    <script src="{{ asset('assets/home_admin/vendors/pdfmake/build/pdfmake.min.js') }}"></script>
    <script src="{{ asset('assets/home_admin/vendors/pdfmake/build/vfs_fonts.js') }}"></script>